export let oldArray = [
    {name:"Aave" , img:"images2/aave-logo.png", description: "AAVE is a decentralized finance platform where users can borrow a range of crypto currencies , as well as lend assets in exchange for interest payments. All without needing a middleman. ", founder: "Stani Kulechov" , whitePaper:"https://github.com/aave/aave-protocol/blob/master/docs/Aave_Protocol_Whitepaper_v1_0.pdf", released: "11/2017" ,   },
    {name:"Algorand" , img:"images2/algorand-logo.png", description:"Algorand is an open-source, payments-focused blockchain network that aims to solve one of the most persistent problems facing cryptocurrency: scalability. To do that, Algorand employs a novel, more scalable form of “proof-of-stake,” a consensus mechanism that’s critical for securing blockchains and making sure no one can create new tokens out of thin air that they didn’t earn. " , founder:"Silvio Micali", whitePaper:"https://arxiv.org/abs/1607.01341", released:"06/2019", symbol:"ALGO"  },
    {name:"Avalanche" , img:"images2/avalanche-logo.png", description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Axie Infinity" , img:"images2/axie-infinity-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Binance" , img:"images2/binance-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Bitcoin Cash" , img:"images2/bitcoin-cash-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Bitcoin" , img:"images2/bitcoin-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Bnb" , img:"images2/bnb-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Cardano" , img:"images2/cardano-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Chainlink" , img:"images2/chainlink-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Cosmos" , img:"images2/cosmos-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Crypto.com Coin" , img:"images2/crypto-com-coin-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Dai" , img:"images2/dai-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""} ,
    {name:"Decentraland" , img:"images2/decentraland-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"DistrictOx" , img:"images2/districtOx-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Dogecoin" , img:"images2/dogecoin-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Elrond" , img:"images2/elrond-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Eos" , img:"images2/eos-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Ethereum Classic" , img:"images2/ethereum-classic-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Filecoin" , img:"images2/filecoin-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Flow" , img:"images2/flow-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Ftx" , img:"images2/ftx-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Hedera" , img:"images2/hedera-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Helium" , img:"images2/helium-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Huobi" , img:"images2/huobi-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Internet Computer" , img:"images2/internet-computer-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Klaytn" , img:"images2/klaytn-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Kucoin Token" , img:"images2/kucoin-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Litecoin" , img:"images2/litecoin-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Maker" , img:"images2/maker-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Monero" , img:"images2/monero-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Near" , img:"images2/near-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Polkadot" , img:"images2/polkadot-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Polygon" , img:"images2/polygon-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Shiba inu" , img:"images2/shiba-inu-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Solana" , img:"images2/solana-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Stellar" , img:"images2/stellar-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Tether" , img:"images2/tether-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Tezos" , img:"images2/tezos-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"The Sandbox" , img:"images2/the-sandbox-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Theta Network" , img:"images2/theta-network-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Tron" , img:"images2/tron-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"TrueUSD" , img:"images2/trueusd-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Uniswap" , img:"images2/uniswap-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Unus Sed Leo" , img:"images2/unus-sed-leo-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"USD Coin" , img:"images2/usd-coin-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Vechain" , img:"images2/vechain-logo.png", description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Wrapped Bitcoin" , img:"images2/wrapped-bitcoin-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"XRP" , img:"images2/xrp-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""},
    {name:"Zcash" , img:"images2/zcash-logo.png" , description:"", founder:"", whitePaper:"", released:"", symbol:""}
];

